title: "V A M P I R E\u00A0\u00A0\u00A0W O R K D A Y"
description: >-
  Extra ordinary thoughts from my little corner of the universe. Just working
  for the Weekend kind of sucks.
url: 'https://vampireworkday.com'
baseurl: ''
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default
search: 'true'
permalink: '/:categories/:title/'
paginate: 5
paginate_path: '/page:num/'
author:
  name: Mike Stevens
  avatar: /assets/images/mike-stevens-profile.png
  bio: Extra ordinary thoughts from my little corner of the universe.
  location: Peachtree City, GA USA
  links:
    - label: Email
      icon: fas fa-fw fa-envelope-square
      url: mailto:blog@vampireworkday.com
      target: _blank
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/mike11stevens
      target: _blank
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://linkedin.com/in/mikestevens
      target: _blank
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/mike11stevens
      target: _blank
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-admin
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
  - jemoji
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
      share: true
      related: true
  - scope:
      path: ''
      type: pages
    values:
      layout: single
      author_profile: true
      show_date: true
jekyll_admin:
  homepage: posts
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
